version: '3'

services:

  web:
    tty: true
    environment:
      DATABASE_URL: postgres://admin:admin@db/app
      HEROKU_APP_NAME: app
      HEROKU_DOMAIN: localhost
      # dev environments
      FLASK_APP: app:app
      FLASK_DEBUG: "1"
    build: .
    image: bot-web
    ports: ["5000:5000"]
    volumes: ['.:/work']
    depends_on: ["db"]
    entrypoint: flask
    command: run --host 0.0.0.0

  db:
    image: postgres
    restart: always
    ports: ["5432:5432"]
    volumes:
      - ./.database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
